// src/app/footer/footer.component.ts
import {Component, ViewEncapsulation} from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class FooterComponent {}

<footer class="container mx-auto px-2 py-5">
  <p class="text-center text-sm font-medium opacity-80 font-stretch-expanded">
    <!-- use inline-blocks to have line breaks between spans -->
    <a
      href="http://hs.hiveswap.com/ezodiac/index.php"
      target="_blank"
      class="link inline-block"
      >The Extended Zodiac</a
    >
    &ngsp;
    <span class="inline-block">owned by</span>
    &ngsp;
    <span class="inline-block">What Pumpkin Games Inc.</span>
  </p>
</footer>

// src/routes/Footer.svelte
<script lang="ts">
	import Link from '$lib/ui/Link.svelte';
</script>

<footer class="bg-neutral-200">
	<div class="container mx-auto space-y-3 px-2 py-9">
		<p class="text-center text-sm font-medium opacity-80">
			Source on <Link href="https://github.com/Rocker-Mitchell/aspect-quiz-analyzer" target="_blank"
				>GitHub</Link
			>
		</p>

		<p class="text-center text-sm font-medium opacity-80">
			<!-- use inline blocks to have line breaks between spans -->
			<Link href="http://hs.hiveswap.com/ezodiac/index.php" target="_blank" inlineBlock
				>The Extended Zodiac</Link
			>
			<span class="inline-block">owned by</span>
			<span class="inline-block">What Pumpkin Games Inc.</span>
		</p>
	</div>
</footer>
